<?php
/**
 * Guarded fix: same mechanism as fix-face-category-banner.php,
 * fix-eyes-category-banner.php, and fix-lips-category-banner.php - the
 * category banner mapping lives in the "Code Snippets" plugin's custom
 * wp_snippets table (id=7, "Lunaci Category Banners"), a hardcoded PHP
 * array mapping product_cat slugs to attachment IDs. Replace ONLY the
 * 'nails' entry's attachment ID with the new user-supplied banner photo
 * (already uploaded and size-regenerated by the workflow step before this
 * script runs, attachment ID passed via env var), leaving
 * face/eyes/lips untouched.
 */

global $wpdb;

$new_attachment = getenv( 'LUNACI_NAILS_BANNER_MEDIA_ID' );
if ( false === $new_attachment || '' === $new_attachment || ! is_numeric( $new_attachment ) ) {
	echo "ABORT: expected LUNACI_NAILS_BANNER_MEDIA_ID env var\n";
	exit( 1 );
}
$new_attachment = (int) $new_attachment;

echo "--- verify new attachment ---\n";
$new_att_post = get_post( $new_attachment );
if ( ! $new_att_post || 'attachment' !== $new_att_post->post_type ) {
	echo "ABORT: new attachment {$new_attachment} not found or not an attachment\n";
	exit( 1 );
}
$new_url = wp_get_attachment_url( $new_attachment );
echo "new attachment {$new_attachment} resolved url: {$new_url}\n";

$table         = $wpdb->prefix . 'snippets';
$snippet_id    = 7;
$nails_pattern = "/('nails'\\s*=>\\s*)(\\d+)(\\s*,)/";

echo "\n--- STEP A: PREPARE ---\n";
$current_code = $wpdb->get_var( $wpdb->prepare( "SELECT code FROM {$table} WHERE id = %d", $snippet_id ) );
if ( null === $current_code ) {
	echo "ABORT: snippet id={$snippet_id} not found in {$table}\n";
	exit( 1 );
}
if ( ! preg_match( $nails_pattern, $current_code, $m ) ) {
	echo "ABORT: could not find a 'nails' => <id>, entry in snippet code - format changed?\n";
	exit( 1 );
}
$old_id = (int) $m[2];
echo "current 'nails' banner attachment ID: {$old_id}\n";

if ( $old_id === $new_attachment ) {
	echo "ABORT: 'nails' banner is already the new attachment - refusing to proceed (already fixed?)\n";
	exit( 1 );
}
echo "OK: preconditions satisfied\n";

echo "\n--- STEP B: COMMIT ---\n";
$fresh_code = $wpdb->get_var( $wpdb->prepare( "SELECT code FROM {$table} WHERE id = %d", $snippet_id ) );
if ( $fresh_code !== $current_code ) {
	echo "ABORT: snippet code changed since STEP A (concurrent edit) - refusing to write\n";
	exit( 1 );
}

$replace_count = 0;
$new_code      = preg_replace( $nails_pattern, '${1}' . $new_attachment . '${3}', $fresh_code, -1, $replace_count );
if ( 1 !== $replace_count ) {
	echo "ABORT: expected exactly 1 replacement of the 'nails' entry, got {$replace_count}\n";
	exit( 1 );
}

$updated = $wpdb->update( $table, array( 'code' => $new_code ), array( 'id' => $snippet_id ), array( '%s' ), array( '%d' ) );
if ( false === $updated ) {
	echo "ABORT: \$wpdb->update() failed: {$wpdb->last_error}\n";
	exit( 1 );
}
echo "OK: \$wpdb->update() rows affected: {$updated}\n";

wp_cache_flush();

echo "\n--- STEP C: VERIFY ---\n";
$verify_code = $wpdb->get_var( $wpdb->prepare( "SELECT code FROM {$table} WHERE id = %d", $snippet_id ) );
if ( ! preg_match( $nails_pattern, $verify_code, $vm ) ) {
	echo "FAIL: could not find a 'nails' => <id>, entry after write\n";
	exit( 1 );
}
$verify_id = (int) $vm[2];
echo "verify 'nails' banner attachment ID: {$verify_id}\n";

if ( $verify_id !== $new_attachment ) {
	echo "FAIL: 'nails' banner attachment ID not updated to expected new attachment\n";
	exit( 1 );
}

echo "\n=====================================================================\n";
echo "FINAL RESULT: SUCCESS\n";
