<?php
/**
 * Guarded fix: replace the AI-rendered featured images on the WooCommerce
 * "LUNACI Eyebrow Pencil" (product 497, old attachment 251) and
 * "LUNACI Eye Pencil" (product 501, old attachment 240) products with the
 * user-supplied real product photography, already uploaded and
 * size-regenerated by the workflow step before this script runs
 * (attachment IDs passed via env vars).
 *
 * Unlike the Elementor page fixes elsewhere in this session, WooCommerce
 * product images are set via the standard featured-image mechanism
 * (_thumbnail_id postmeta), not via _elementor_data JSON surgery, so no
 * Elementor element-cache concerns apply here.
 */

$eyebrow_product_id = 497;
$eye_product_id      = 501;
$old_eyebrow_attachment = 251;
$old_eye_attachment     = 240;

$new_eyebrow_attachment = getenv( 'LUNACI_EYEBROW_MEDIA_ID' );
$new_eye_attachment     = getenv( 'LUNACI_EYE_MEDIA_ID' );

if ( false === $new_eyebrow_attachment || '' === $new_eyebrow_attachment || ! is_numeric( $new_eyebrow_attachment ) ) {
	echo "ABORT: expected LUNACI_EYEBROW_MEDIA_ID env var\n";
	exit( 1 );
}
if ( false === $new_eye_attachment || '' === $new_eye_attachment || ! is_numeric( $new_eye_attachment ) ) {
	echo "ABORT: expected LUNACI_EYE_MEDIA_ID env var\n";
	exit( 1 );
}
$new_eyebrow_attachment = (int) $new_eyebrow_attachment;
$new_eye_attachment     = (int) $new_eye_attachment;

$targets = array(
	array(
		'label'          => 'LUNACI Eyebrow Pencil',
		'product_id'     => $eyebrow_product_id,
		'old_attachment' => $old_eyebrow_attachment,
		'new_attachment' => $new_eyebrow_attachment,
	),
	array(
		'label'          => 'LUNACI Eye Pencil',
		'product_id'     => $eye_product_id,
		'old_attachment' => $old_eye_attachment,
		'new_attachment' => $new_eye_attachment,
	),
);

$overall_success = true;

foreach ( $targets as $t ) {
	echo "\n=====================================================================\n";
	echo "PRODUCT {$t['product_id']} ({$t['label']})\n";
	echo "=====================================================================\n";

	echo "--- STEP A: PREPARE ---\n";
	$new_att_post = get_post( $t['new_attachment'] );
	if ( ! $new_att_post || 'attachment' !== $new_att_post->post_type ) {
		echo "ABORT: new attachment {$t['new_attachment']} not found or not an attachment\n";
		$overall_success = false;
		continue;
	}
	$new_url = wp_get_attachment_url( $t['new_attachment'] );
	echo "new attachment {$t['new_attachment']} resolved url: {$new_url}\n";

	$current_thumb = get_post_meta( $t['product_id'], '_thumbnail_id', true );
	echo "current _thumbnail_id: " . var_export( $current_thumb, true ) . "  (expected old: {$t['old_attachment']})\n";
	if ( (string) $current_thumb !== (string) $t['old_attachment'] ) {
		echo "ABORT: current featured image is not the expected old attachment - refusing to overwrite unexpected state\n";
		$overall_success = false;
		continue;
	}
	echo "OK: preconditions satisfied\n";

	echo "--- STEP B: COMMIT ---\n";
	$fresh_thumb = get_post_meta( $t['product_id'], '_thumbnail_id', true );
	if ( (string) $fresh_thumb !== (string) $current_thumb ) {
		echo "ABORT: featured image changed since STEP A (concurrent edit) - refusing to write\n";
		$overall_success = false;
		continue;
	}

	$set_ok = set_post_thumbnail( $t['product_id'], $t['new_attachment'] );
	if ( ! $set_ok ) {
		echo "ABORT: set_post_thumbnail() returned false\n";
		$overall_success = false;
		continue;
	}
	echo "OK: set_post_thumbnail() succeeded\n";

	clean_post_cache( $t['product_id'] );
	if ( function_exists( 'wc_delete_product_transients' ) ) {
		wc_delete_product_transients( $t['product_id'] );
	}

	echo "--- STEP C: VERIFY ---\n";
	$verify_thumb = get_post_meta( $t['product_id'], '_thumbnail_id', true );
	echo "verify _thumbnail_id: " . var_export( $verify_thumb, true ) . "\n";
	if ( (string) $verify_thumb !== (string) $t['new_attachment'] ) {
		echo "FAIL: featured image not updated to expected new attachment\n";
		$overall_success = false;
		continue;
	}

	$verify_src = wp_get_attachment_image_src( $t['new_attachment'], 'woocommerce_thumbnail' );
	echo "woocommerce_thumbnail src now: " . ( $verify_src ? $verify_src[0] . " ({$verify_src[1]}x{$verify_src[2]})" : 'FALSE' ) . "\n";
	if ( ! $verify_src ) {
		$overall_success = false;
	}
}

wp_cache_flush();

echo "\n=====================================================================\n";
if ( $overall_success ) {
	echo "FINAL RESULT: SUCCESS\n";
} else {
	echo "FINAL RESULT: FAILURE - see per-product results above\n";
	exit( 1 );
}
