<?php
/**
 * Guarded fix: replace the featured image on the "Compact Powder"
 * WooCommerce products (EN post 325 "LUNACI Compact Powder", ES post 718
 * "Polvo Compacto LUNACI") with the user-supplied real product
 * photography, already uploaded and size-regenerated by the workflow step
 * before this script runs (attachment ID passed via env var). Both
 * language products reuse the SAME attachment as their featured image -
 * same pattern as fix-eyeliner-real-photo.php.
 */

$new_attachment = getenv( 'LUNACI_COMPACT_POWDER_MEDIA_ID' );
if ( false === $new_attachment || '' === $new_attachment || ! is_numeric( $new_attachment ) ) {
	echo "ABORT: expected LUNACI_COMPACT_POWDER_MEDIA_ID env var\n";
	exit( 1 );
}
$new_attachment = (int) $new_attachment;

$targets = array(
	325 => 'EN LUNACI Compact Powder',
	718 => 'ES Polvo Compacto LUNACI',
);

echo "--- verify new attachment ---\n";
$new_att_post = get_post( $new_attachment );
if ( ! $new_att_post || 'attachment' !== $new_att_post->post_type ) {
	echo "ABORT: new attachment {$new_attachment} not found or not an attachment\n";
	exit( 1 );
}
$new_url = wp_get_attachment_url( $new_attachment );
echo "new attachment {$new_attachment} resolved url: {$new_url}\n";

$overall_success = true;

foreach ( $targets as $product_id => $label ) {
	echo "\n=====================================================================\n";
	echo "PRODUCT {$product_id} ({$label})\n";
	echo "=====================================================================\n";

	echo "--- STEP A: PREPARE ---\n";
	$product = get_post( $product_id );
	if ( ! $product || 'product' !== $product->post_type ) {
		echo "ABORT: product {$product_id} not found or not a product\n";
		$overall_success = false;
		continue;
	}
	echo "confirmed product title: '{$product->post_title}'\n";

	$old_thumb = get_post_meta( $product_id, '_thumbnail_id', true );
	echo "current (old) _thumbnail_id: " . var_export( $old_thumb, true ) . "\n";

	if ( (string) $old_thumb === (string) $new_attachment ) {
		echo "ABORT: featured image is already the new attachment - refusing to proceed (already fixed?)\n";
		$overall_success = false;
		continue;
	}
	echo "OK: preconditions satisfied\n";

	echo "--- STEP B: COMMIT ---\n";
	$fresh_thumb = get_post_meta( $product_id, '_thumbnail_id', true );
	if ( (string) $fresh_thumb !== (string) $old_thumb ) {
		echo "ABORT: featured image changed since STEP A (concurrent edit) - refusing to write\n";
		$overall_success = false;
		continue;
	}

	$set_ok = set_post_thumbnail( $product_id, $new_attachment );
	if ( ! $set_ok ) {
		echo "ABORT: set_post_thumbnail() returned false\n";
		$overall_success = false;
		continue;
	}
	echo "OK: set_post_thumbnail() succeeded\n";

	clean_post_cache( $product_id );
	if ( function_exists( 'wc_delete_product_transients' ) ) {
		wc_delete_product_transients( $product_id );
	}

	echo "--- STEP C: VERIFY ---\n";
	$verify_thumb = get_post_meta( $product_id, '_thumbnail_id', true );
	echo "verify _thumbnail_id: " . var_export( $verify_thumb, true ) . "\n";
	if ( (string) $verify_thumb !== (string) $new_attachment ) {
		echo "FAIL: featured image not updated to expected new attachment\n";
		$overall_success = false;
		continue;
	}

	$verify_src = wp_get_attachment_image_src( $new_attachment, 'woocommerce_thumbnail' );
	echo "woocommerce_thumbnail src now: " . ( $verify_src ? $verify_src[0] . " ({$verify_src[1]}x{$verify_src[2]})" : 'FALSE' ) . "\n";
	if ( ! $verify_src ) {
		$overall_success = false;
	}
}

wp_cache_flush();

echo "\n=====================================================================\n";
if ( $overall_success ) {
	echo "FINAL RESULT: SUCCESS\n";
} else {
	echo "FINAL RESULT: FAILURE - see per-product results above\n";
	exit( 1 );
}
