<?php
/**
 * Guarded fix: the Face category banner is rendered by a "Code Snippets"
 * plugin snippet (id=7, "Lunaci Category Banners") stored in the custom
 * wp_snippets table (NOT wp_posts/WPCode) - a hardcoded PHP array mapping
 * product_cat slugs to attachment IDs:
 *   $banners = array('face'=>633, 'eyes'=>635, 'lips'=>631, 'nails'=>629);
 * Replace ONLY the 'face' entry's attachment ID with the new user-supplied
 * banner photo (already uploaded and size-regenerated by the workflow step
 * before this script runs, attachment ID passed via env var), leaving the
 * eyes/lips/nails entries and everything else in the snippet untouched.
 */

global $wpdb;

$new_attachment = getenv( 'LUNACI_FACE_BANNER_MEDIA_ID' );
if ( false === $new_attachment || '' === $new_attachment || ! is_numeric( $new_attachment ) ) {
	echo "ABORT: expected LUNACI_FACE_BANNER_MEDIA_ID env var\n";
	exit( 1 );
}
$new_attachment = (int) $new_attachment;

echo "--- verify new attachment ---\n";
$new_att_post = get_post( $new_attachment );
if ( ! $new_att_post || 'attachment' !== $new_att_post->post_type ) {
	echo "ABORT: new attachment {$new_attachment} not found or not an attachment\n";
	exit( 1 );
}
$new_url = wp_get_attachment_url( $new_attachment );
echo "new attachment {$new_attachment} resolved url: {$new_url}\n";

$table       = $wpdb->prefix . 'snippets';
$snippet_id  = 7;
$face_pattern = "/('face'\\s*=>\\s*)(\\d+)(\\s*,)/";

echo "\n--- STEP A: PREPARE ---\n";
$current_code = $wpdb->get_var( $wpdb->prepare( "SELECT code FROM {$table} WHERE id = %d", $snippet_id ) );
if ( null === $current_code ) {
	echo "ABORT: snippet id={$snippet_id} not found in {$table}\n";
	exit( 1 );
}
if ( ! preg_match( $face_pattern, $current_code, $m ) ) {
	echo "ABORT: could not find a 'face' => <id>, entry in snippet code - format changed?\n";
	exit( 1 );
}
$old_id = (int) $m[2];
echo "current 'face' banner attachment ID: {$old_id}\n";

if ( $old_id === $new_attachment ) {
	echo "ABORT: 'face' banner is already the new attachment - refusing to proceed (already fixed?)\n";
	exit( 1 );
}
echo "OK: preconditions satisfied\n";

echo "\n--- STEP B: COMMIT ---\n";
$fresh_code = $wpdb->get_var( $wpdb->prepare( "SELECT code FROM {$table} WHERE id = %d", $snippet_id ) );
if ( $fresh_code !== $current_code ) {
	echo "ABORT: snippet code changed since STEP A (concurrent edit) - refusing to write\n";
	exit( 1 );
}

$replace_count = 0;
$new_code      = preg_replace( $face_pattern, '${1}' . $new_attachment . '${3}', $fresh_code, -1, $replace_count );
if ( 1 !== $replace_count ) {
	echo "ABORT: expected exactly 1 replacement of the 'face' entry, got {$replace_count}\n";
	exit( 1 );
}

$updated = $wpdb->update( $table, array( 'code' => $new_code ), array( 'id' => $snippet_id ), array( '%s' ), array( '%d' ) );
if ( false === $updated ) {
	echo "ABORT: \$wpdb->update() failed: {$wpdb->last_error}\n";
	exit( 1 );
}
echo "OK: \$wpdb->update() rows affected: {$updated}\n";

wp_cache_flush();

echo "\n--- STEP C: VERIFY ---\n";
$verify_code = $wpdb->get_var( $wpdb->prepare( "SELECT code FROM {$table} WHERE id = %d", $snippet_id ) );
if ( ! preg_match( $face_pattern, $verify_code, $vm ) ) {
	echo "FAIL: could not find a 'face' => <id>, entry after write\n";
	exit( 1 );
}
$verify_id = (int) $vm[2];
echo "verify 'face' banner attachment ID: {$verify_id}\n";

if ( $verify_id !== $new_attachment ) {
	echo "FAIL: 'face' banner attachment ID not updated to expected new attachment\n";
	exit( 1 );
}

echo "verify: 'eyes', 'lips', 'nails' entries unchanged: " .
	( false !== strpos( $verify_code, "'eyes'  => 635," ) &&
	  false !== strpos( $verify_code, "'lips'  => 631," ) &&
	  false !== strpos( $verify_code, "'nails' => 629," ) ? 'yes' : 'CHECK MANUALLY' ) . "\n";

echo "\n=====================================================================\n";
echo "FINAL RESULT: SUCCESS\n";
