<?php
/**
 * Guarded fix: replace the featured image on the WooCommerce "Eyeliner"
 * product with the user-supplied real product photography (a liquid
 * eyeliner bottle with brush applicator), already uploaded and
 * size-regenerated by the workflow step before this script runs
 * (attachment ID passed via env var).
 *
 * Unlike fix-eyebrow-eye-pencil-real-photos.php, the old attachment ID is
 * not hardcoded here - the product is located by title (LIKE '%yeliner%',
 * expecting exactly one match) and its CURRENT _thumbnail_id is read at
 * runtime and used as the STEP A/B race-condition guard value, since we
 * don't know it in advance.
 */

global $wpdb;

$new_attachment = getenv( 'LUNACI_EYELINER_MEDIA_ID' );
if ( false === $new_attachment || '' === $new_attachment || ! is_numeric( $new_attachment ) ) {
	echo "ABORT: expected LUNACI_EYELINER_MEDIA_ID env var\n";
	exit( 1 );
}
$new_attachment = (int) $new_attachment;

echo "--- STEP A: PREPARE ---\n";

$products = $wpdb->get_results(
	"SELECT ID, post_title FROM {$wpdb->posts} WHERE post_type = 'product' AND post_status = 'publish' AND post_title LIKE '%yeliner%'",
	ARRAY_A
);

if ( 1 !== count( $products ) ) {
	echo "ABORT: expected exactly 1 published product matching 'eyeliner', found " . count( $products ) . "\n";
	foreach ( $products as $p ) {
		echo "  ID={$p['ID']} title='{$p['post_title']}'\n";
	}
	exit( 1 );
}

$product_id    = (int) $products[0]['ID'];
$product_title = $products[0]['post_title'];
echo "found product ID={$product_id} title='{$product_title}'\n";

$new_att_post = get_post( $new_attachment );
if ( ! $new_att_post || 'attachment' !== $new_att_post->post_type ) {
	echo "ABORT: new attachment {$new_attachment} not found or not an attachment\n";
	exit( 1 );
}
$new_url = wp_get_attachment_url( $new_attachment );
echo "new attachment {$new_attachment} resolved url: {$new_url}\n";

$old_thumb = get_post_meta( $product_id, '_thumbnail_id', true );
echo "current (old) _thumbnail_id: " . var_export( $old_thumb, true ) . "\n";

if ( (string) $old_thumb === (string) $new_attachment ) {
	echo "ABORT: featured image is already the new attachment - refusing to proceed (already fixed?)\n";
	exit( 1 );
}
echo "OK: preconditions satisfied\n";

echo "--- STEP B: COMMIT ---\n";
$fresh_thumb = get_post_meta( $product_id, '_thumbnail_id', true );
if ( (string) $fresh_thumb !== (string) $old_thumb ) {
	echo "ABORT: featured image changed since STEP A (concurrent edit) - refusing to write\n";
	exit( 1 );
}

$set_ok = set_post_thumbnail( $product_id, $new_attachment );
if ( ! $set_ok ) {
	echo "ABORT: set_post_thumbnail() returned false\n";
	exit( 1 );
}
echo "OK: set_post_thumbnail() succeeded\n";

clean_post_cache( $product_id );
if ( function_exists( 'wc_delete_product_transients' ) ) {
	wc_delete_product_transients( $product_id );
}

echo "--- STEP C: VERIFY ---\n";
$verify_thumb = get_post_meta( $product_id, '_thumbnail_id', true );
echo "verify _thumbnail_id: " . var_export( $verify_thumb, true ) . "\n";
if ( (string) $verify_thumb !== (string) $new_attachment ) {
	echo "FAIL: featured image not updated to expected new attachment\n";
	exit( 1 );
}

$verify_src = wp_get_attachment_image_src( $new_attachment, 'woocommerce_thumbnail' );
echo "woocommerce_thumbnail src now: " . ( $verify_src ? $verify_src[0] . " ({$verify_src[1]}x{$verify_src[2]})" : 'FALSE' ) . "\n";

wp_cache_flush();

if ( $verify_src ) {
	echo "\nFINAL RESULT: SUCCESS\n";
} else {
	echo "\nFINAL RESULT: FAILURE\n";
	exit( 1 );
}
